name: prayer_times
description: Demonstrates how to use the alarm plugin.
version: 0.1.2

publish_to: 'none'

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  alarm: ^4.0.0-dev.2
  archive: ^3.6.1
  awesome_notifications: ^0.9.3+1
  awesome_notifications_core: ^0.9.3
  bottom_picker: ^2.8.0
  clipboard: ^0.1.3
  connectivity_plus: ^6.0.5
  cupertino_icons: ^1.0.8
  dio: ^5.6.0
  email_validator: ^3.0.0
  fluentui_system_icons: ^1.1.252
  flutter:
    sdk: flutter
  flutter_animate: ^4.5.0
  flutter_foreground_task: ^8.4.0
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^4.0.0
  flutter_native_splash: ^2.4.1
  flutter_polyline_points: ^2.1.0
  fluttertoast: ^8.2.8
  font_awesome_flutter: ^10.7.0
  gap: ^3.0.1
  geolocator: ^12.0.0
  get: ^5.0.0-release-candidate-9
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  http: ^1.2.2
  intl: ^0.19.0
  path_provider: ^2.1.4
  permission_handler: ^11.1.0
  shared_preferences: ^2.3.2
  simple_icons: ^10.1.3
  url_launcher: ^6.2.5
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^5.1.0

flutter:

  uses-material-design: true

  assets:
    - assets/adan_fajr.mp3
    - assets/adan.mp3
    - assets/allow_location.png
    - assets/cities.json
    - assets/No_Internet_Connection.png
